[project]
name = "speak-to-me"
version = "0.1.0"
requires-python = "==3.13.*"
dependencies = [
    "google-genai",
    "google-cloud-speech",
    "google-cloud-texttospeech",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "mypy"
]